// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2RCK5xIPvk6MBS5EdtIpPMvjTphJ9sgY',
    appId: '1:415370018046:web:0d1078a85f881cb87b39af',
    messagingSenderId: '415370018046',
    projectId: 'budgey-f9154',
    authDomain: 'budgey-f9154.firebaseapp.com',
    storageBucket: 'budgey-f9154.appspot.com',
    measurementId: 'G-QRW8WDPWJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaSbZSg6-DwqCgZXKdnaxD1iGzEtabWEU',
    appId: '1:415370018046:android:c1edd3d9e461a9ba7b39af',
    messagingSenderId: '415370018046',
    projectId: 'budgey-f9154',
    storageBucket: 'budgey-f9154.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATAjDrQXKp0TZ4b4K9oC1TWJsWG9WhCa0',
    appId: '1:415370018046:ios:cd923b1fd22dbe7b7b39af',
    messagingSenderId: '415370018046',
    projectId: 'budgey-f9154',
    storageBucket: 'budgey-f9154.appspot.com',
    iosClientId: '415370018046-btduksatahch3pd6mnc39keekggcvups.apps.googleusercontent.com',
    iosBundleId: 'com.example.managment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATAjDrQXKp0TZ4b4K9oC1TWJsWG9WhCa0',
    appId: '1:415370018046:ios:cd923b1fd22dbe7b7b39af',
    messagingSenderId: '415370018046',
    projectId: 'budgey-f9154',
    storageBucket: 'budgey-f9154.appspot.com',
    iosClientId: '415370018046-btduksatahch3pd6mnc39keekggcvups.apps.googleusercontent.com',
    iosBundleId: 'com.example.managment',
  );
}
